name: CI/CD

on:
  push:
    branches: [main]

env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"

jobs:
  Variables:
    runs-on: ubuntu-latest

    env:
      MY_JOB_VARIABLE: "This is a job-level variable"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display all variable scopes
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
        run: |
          echo "Workflow-level variable: $MY_WORKFLOW_VARIABLE"
          echo "Job-level variable: $MY_JOB_VARIABLE"
          echo "Step-level variable: $MY_STEP_VARIABLE"

      - name: Access step variable in another step
        run: |
          echo "Accessing step-level variable (should be empty): $MY_STEP_VARIABLE"
          echo "Workflow-level variable still available: $MY_WORKFLOW_VARIABLE"
